### ISSUE TITLE
Chromedriver version 114.0.5735.133

### ISSUE THREAD

**Issue by nao-riku** [danielkaiser/python-chromedriver-binary#26]
Shouldn't the latest-patch-versions-per-build-with-downloads.json be used for version 115 and above, as well as 114.0.5735.133?

The file "https://chromedriver.storage.googleapis.com/114.0.5735.133/chromedriver_〇〇.zip" does not exist!

**Comment by danielkaiser** [comment]
Hi @nao-riku,

unfortunately, the Chromedriver for major version 114 is nowhere to be found. If you have a closer look at the mentioned [latest-patch-versions-per-build-with-downloads.json](https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build-with-downloads.json) file, you will notice that for 114.x releases only Chrome but not Chromedriver downloads are listed:

![image](https://github.com/danielkaiser/python-chromedriver-binary/assets/9868673/60a44be5-d3a2-44a6-9ce5-9d73f6f98497)

Whereas for 115.x both are available:

![image](https://github.com/danielkaiser/python-chromedriver-binary/assets/9868673/feb0060b-83da-46a9-b2ad-9ffa6c02b80a)

Because the download is neither available on the old location nor the new, I decided to use the new JSON endpoints starting with version 115 as it is mentioned [here](https://chromedriver.chromium.org/#h.8cjh6c3ay1qq):

> Starting with M115 the latest Chrome + ChromeDriver releases per release channel (Stable, Beta, Dev, Canary) are available at[ the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). For automated version downloading one can use the convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json).

**Comment by nao-riku** [comment]
I have no choice but to update to version 115......

Thank you so much!
