### ISSUE TITLE
Old versions of chromedriver pulled down

### ISSUE THREAD

**Issue by pgclosie** [danielkaiser/python-chromedriver-binary#9]
Old version of chromedriver pulled down.

Steps:

  - pip install chromedriver-binary==73.0.3683.68.0
  - Check C:\Python27\Lib\site-packages\chromedriver_binary
  - chromedriver.exe version is 2.37.544315

This is occurring on Windows7.
I've tested on a Win10 machine and it's pulling the specified version correctly.

Does anyone have any ideas why this would be?

**Comment by danielkaiser** [comment]
I can only test on Linux, but there the correct version is downloaded.

One possible explanation is that you already have a binary distribution of chromedriver(.exe) that is found in the path during the installation. In this case the download is skipped because the user provided version is preferred over the download.

I will tag a new version later today anyway so I probably will add a version check to make sure the user provided chromedriver matches the package version, but I won't backport this code to the older versions.

So could you as a test (or hopefully workaround) make sure to uninstall existing chromedriver binaries or remove them from the executable search path?

**Comment by pgclosie** [comment]
Hey Daniel,
Thanks for the info.  I didn't realise that the download is skipped if a version already exists.  I'll need to try that out but it could be the reason for my problem.  

Is there a reason for the chromedriver that is found in the path taking priority?  Does this mean that if we wanted to upgrade from a previous version it wouldn't be possible?

This is the scenario I'm trying to achieve.

Thanks

**Comment by danielkaiser** [comment]
If you update from a previous version it should be no problem, because `pip install` uninstalls the old version before installing the new one which also deletes the old chromedriver.exe before running setup.py of the new version.

if you provide a `chromedriver.exe` executable that is found in the search path (installed from a different source) it skips the download. Since the latest release (912af775a9d8c698a8cb66956295f7e554204c6d) the version of such a binary is checked, but for 73.x you could try to run
```
set PATH=C:\Python27\;C:\Python27\Scripts\
pip install chromedriver-binary==73.0.3683.68.0
```
to make sure the setup script does not find an outdated chromedriver.exe from somewhere in your system.

**Comment by pgclosie** [comment]
Hey @danielkaiser 

The fix has worked.!  I've retested in Win 7 with an existing older chromedriver.exe included in the path.
The latest version of chromedriver is now downloaded i.e. 75.  

This leads me on to another question/request.  It would be really good if the default version would target the latest stable version of chromedriver/chrome (currently 74).  We generally test on the latest _stable_ version.

**Comment by snicker** [comment]
I agree with @pgclosie on stable vs dev being latest for this package.

 Could I suggest a secondary PyPI package `chromedriver-binary-dev` that pins to the dev release of chromedriver? I have automation that uses chromedriver, and the system Chrome will auto update. Got flooded with errors this morning. I would like to just auto-upgrade this package as new stable versions come out but don't have a way to do that at this time.

**Comment by snicker** [comment]
As a followup, after reading though PEP 440, a separate package should not be required, as long as you version the dev releases of chromedriver in your PyPI package as a developmental release:

https://www.python.org/dev/peps/pep-0440/#developmental-releases

by default, `pip install chromedriver-binary` will always install the latest stable release, ignoring developmental releases.

**Comment by danielkaiser** [comment]
Is it okay if I close this issue because the remaining open question is now in #10?

**Comment by pgclosie** [comment]
> 
> 
> Is it okay if I close this issue because the remaining open question is now in #10?

Done! Thanks.
